5. Arrays and indexing

5.1 Creating an array

In [1]:
import numpy as np

In [3]:
# Creating a vector
v = np.array([1, 2, 3])
v

array([1, 2, 3])

In [4]:
# Creating a matrix. Put each row of a matrix in square brackets
v = np.array([[1, 2, 3], [4, 5, 6]])
v

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# Regularly spaced 1D vectors
# Regular spaced array with a chosen step size
v = np.arange(1, 11, 2) # last element is not inculded
v

array([1, 3, 5, 7, 9])

In [9]:
# Regular spaced array with a chosen number of elements
v = np.linspace(1, 10, 10)
v

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
N = 10
v=np.linspace(1,10,N,endpoint=False)
v

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [17]:
# Multidimensional arrays
m = np.zeros([3, 5])
m

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
m = np.ones([3, 5])
m

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# ”Identity” matrix
m= np.eye(5)
m

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
# Diagonal matrix
v = np.array([1, 2, 3])
m = np.diag(v)
m

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

5.2 Array indexing

In [23]:
v = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
v[0]

1

In [25]:
v[9]

10

In [26]:
v[-1]

10

In [ ]:
# Slicing
# First row of A : A[0,:]
# First column of A : A[:, 0]
# Last row of A : A[-1, :] 
# Submatrix contained between the rows 3 and 5 and columns 2 and 4 : A[2:4,1:3]

In [28]:
v = np.linspace(1, 7, 7)
a = np.diag(v)
a

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 0.],
       [0., 0., 0., 0., 0., 6., 0.],
       [0., 0., 0., 0., 0., 0., 7.]])

In [29]:
a[0, :]

array([1., 0., 0., 0., 0., 0., 0.])

In [30]:
a[:, 3]

array([0., 0., 0., 4., 0., 0., 0.])

In [31]:
a[2:4, 1:3]

array([[0., 3.],
       [0., 0.]])

In [34]:
# Slicing with a step
v = np.linspace(1, 50, 50)
v

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [35]:
v[10:20:3]

array([11., 14., 17., 20.])

In [36]:
v[::3]

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25., 28., 31., 34., 37.,
       40., 43., 46., 49.])

In [38]:
# Reshape

a = v.reshape(5,10)
a

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.],
       [31., 32., 33., 34., 35., 36., 37., 38., 39., 40.],
       [41., 42., 43., 44., 45., 46., 47., 48., 49., 50.]])

In [40]:
a[::2, ::4]

array([[ 1.,  5.,  9.],
       [21., 25., 29.],
       [41., 45., 49.]])