6.1 Arithmetic operations
- component-wise,
- matrices involved must have the same shape.

In [1]:
import numpy as np

In [2]:
a = np.diag([1, 2, 3, 5])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 5]])

In [3]:
b = np.eye(4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
a*b

array([[1., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 5.]])

In [5]:
a/b

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ 1., nan, nan, nan],
       [nan,  2., nan, nan],
       [nan, nan,  3., nan],
       [nan, nan, nan,  5.]])

In [6]:
# To check the shape 
np.shape(b)

(4, 4)

6.2 Numpy math functions
- operate component-wise on matrice https://numpy.org/doc/stable/reference/routines.math.html

6.3 Numpy matrix specific functions
- Several of numpy functions are intended for use on arrays (e.g. to realize vector calculus operations) and do not operate component-wise. The most important for us are listed below.
- np.amax(A,axis)
- np.amin(A, axis)

In [7]:
a = np.array([[0., 4., 4., 4.],
              [1., 2., 4., 4.],
              [1., 4., 5., 4.],
              [1., 4., 4., 4.]])
a

array([[0., 4., 4., 4.],
       [1., 2., 4., 4.],
       [1., 4., 5., 4.],
       [1., 4., 4., 4.]])

In [8]:
np.amax(a, 0) # claculte max element in each coulmn

array([1., 4., 5., 4.])

In [9]:
np.sum(a,1) # calculte sum in each row

array([12., 11., 14., 13.])

In [10]:
# Vector algebra functions
# np.dot(x,y) -computes matrix dot product (”proper” linear algebra matrix multiplication) 
# np.cross(x,y) - computes cross product of vectors x and y.
# np.transpose(A) - computes a transpose of matrix A.

6.4 Finding and selecting data in an array

In [11]:
# Maximal and minimal element
# np.max(A)
# np.min(A)

# Index of maximal and minimal element
# np.argmax(A)
# np.argmin(A)

In [12]:
# Maximum location in 2D array

x=np.array([1,3,5,2,4])
np.argmax(x)

2

In [13]:
x = np.array([(14, 29, 34), (42, 5, 46), (1, 38, 44), (52, 16, 5)])

ind = np.argmax(x)
rowind = ind//np.shape(x)[1]
colwind = ind%np.shape(x)[1]
rowind, colwind

(3, 0)

In [14]:
np.shape(x)[1]

3

In [34]:
# Finding relative maxima and minima can be done using scipy package
# argrelmax(A)
# argrelmin(A)

from scipy.signal import argrelmax
x = np.array([2, 1, 2, 3, 2, 0, 1, 0])
argrelmax(x)

(array([3, 6], dtype=int64),)

In [16]:
# Selecting and modifying data satisfying some criteria
x = np.array([(14, 29, 34), (42, 5, 46), (1, 38, 44), (52, 16, 5)])
x

array([[14, 29, 34],
       [42,  5, 46],
       [ 1, 38, 44],
       [52, 16,  5]])

In [17]:
y = x > 40
y

array([[False, False, False],
       [ True, False,  True],
       [False, False,  True],
       [ True, False, False]])

In [18]:
y = x[x > 40]
y

array([42, 46, 44, 52])

In [19]:
5*(x>40)

array([[0, 0, 0],
       [5, 0, 5],
       [0, 0, 5],
       [5, 0, 0]])

Finding indices where condition is met
- Function np.where can be used both to find the indexes of the elements satisfying certain criteria and to modify the data accordingly

In [20]:
x = np.array([(14, 29, 34), (42, 5, 46), (1, 38, 44), (52, 16, 5)])
x

array([[14, 29, 34],
       [42,  5, 46],
       [ 1, 38, 44],
       [52, 16,  5]])

In [21]:
ind=np.where(x>42)
ind

(array([1, 2, 3], dtype=int64), array([2, 2, 0], dtype=int64))

In [22]:
ind[0][2]

3

In [23]:
np.where(x[0,:]==29)[0][0] # Finds first occurence of 29 in x[0,:]

1

In [24]:
# Modifying data using np.where
x = np.array([(14, 29, 34), (42, 5, 46), (1, 38, 44), (52, 16, 5)])
y = np.where(x>42, x, -1)
y

array([[-1, -1, -1],
       [-1, -1, 46],
       [-1, -1, 44],
       [52, -1, -1]])

6.5 Aggregating data.

Aggregation means producing summary data such as averages, sums, maxima and minima, etc. Most frequently used numpy aggregating functions are listed below.

np.amax(A) # Finds maximum of array A
np.max(A) # Identical to np.max
np.min(A) # Finds minimum of A
np.amin(A) # Identical to np.min
np.mean(A) # Averages array A, also works with masked arrays
np.average(A) #similar to np.mean, can compute weighted average, ignores masks
np.sum(A) # Finds sum of elements of A

All aggregating functions take axis parameter, which allows to aggregate data along rows (axis=1) and columns (axis=0). If no axis is specified the aggregation is applied to whole array (e.g. the sum of all elements in an array is computed).

In [25]:
x=np.arange(1,11,1)


In [26]:
x = x.reshape(2, 5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
np.mean(x)

5.5

In [28]:
np.mean(x, axis=1)

array([3., 8.])

In [29]:
np.mean(x, axis=0)

array([3.5, 4.5, 5.5, 6.5, 7.5])

In [30]:
np.max(x,axis=1)

array([ 5, 10])

In [31]:
np.min(x,axis=1)

array([1, 6])

In [32]:
np.sum(x)

55

In [33]:
np.sum(x,axis=0)

array([ 7,  9, 11, 13, 15])